
[tool.poetry]
name = "giraffe"
version = "0.1.0"
description = "Fable Giraffe"
authors = ["Dag Brattli <dag@brattli.net>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.9"
structlog = "^22.1.0"

[tool.poetry.dev-dependencies]
black = {version = "^22.8.0", allow-prereleases = true}
pytest = "^7.1.3"
pytest-asyncio = "^0.19.0"
uvicorn = "^0.18.3"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
