<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <WarnOn>3390;$(WarnOn)</WarnOn>
    <LangVersion>preview</LangVersion>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="../shared/Testing.fs" />
    <Compile Include="TestContext.fs" />
    <Compile Include="../shared/HandlerTests.fs" />
    <Compile Include="../shared/RoutingTests.fs" />
    <Compile Include="Main.fs" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Fable.Core" Version="5.2.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\js\Fable.Giraffe.Js.fsproj" />
  </ItemGroup>
</Project>
