<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <WarnOn>3390;$(WarnOn)</WarnOn>
    <LangVersion>preview</LangVersion>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="../shared/Helpers.fs" />
    <Compile Include="TestContext.fs" />
    <Compile Include="../shared/HandlerTests.fs" />
    <Compile Include="../shared/RoutingTests.fs" />
    <Compile Include="../shared/EndpointTests.fs" />
    <Compile Include="../shared/OpenApiTests.fs" />
    <Compile Include="../shared/RemotingTests.fs" />
    <Compile Include="../shared/McpTests.fs" />
    <Compile Include="Main.fs" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Fable.Core" Version="5.2.0" />
    <PackageReference Include="Scriptorium.Quill" Version="0.7.0" />
    <PackageReference Include="Scriptorium.Nib" Version="0.4.1" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\Fable.Giraffe.Js.fsproj" />
  </ItemGroup>
</Project>
