name: Build and Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 8.x

      - name: Install just
        uses: extractions/setup-just@v3

      - name: Setup
        run: just setup

      - name: Build
        run: just build

      - name: Test
        run: just test
