name: Build and Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.400

      - name: Setup dotnet tools
        run: dotnet tool restore

      - name: Install src dependencies
        run: dotnet restore src

      - name: Install test dependencies
        run: dotnet restore test

      - name: Install pytest runner
        run: pip install pytest

      - name: Install build dependencies
        run: dotnet restore Build.fsproj

      #- name: Check formatting
      #  run: dotnet fantomas . -r --check

      - name: Build
        run: dotnet run Build --configuration Release --no-restore

      - name: Install dependencies
        run: |
          pip install poetry
          poetry install

      - name: Test
        run: dotnet run Test
